fix(setup): pass target list as args instead of single arg
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not support target 'x86_64-unknown-none riscv64gc-unknown-none-elf aarch64-unknown-none aarch64-unknown-none-softfloat x86_64-unknown-linux-gnu riscv64imac-unknown-none-elf loongarch64-unknown-none'