fix(ci): 不再需要 step 内设置 sccache 环境变量
error: could not execute process `sccache /home/runner/.rustup/toolchains/nightly-2024-05-21-x86_64-unknown-linux-gnu/bin/rustc -vV` (never executed)

Caused by:

  No such file or directory (os error 2)
Error: command ["cargo", "install", "--path", ".", "--force"] exited with code 101

Location:

    src/output/norun.rs:68:5