os-checker: fill in Repo::resolve; run cmd test on test-fmt
test run_checker::repo output:

[test-fmt with Fmt checking] exit statusexit status: 0
stdout=[{"name":"/rust/my/os-checker/tmp/test-fmt/src/main.rs","mismatches":[{"original_begin_line":4,"original_end_line":5,"expected_begin_line":4,"expected_end_line":4,"o
riginal":" \nprintln!(\"Hello, world!\");\n","expected":"    println!(\"Hello, world!\");\n"}]},{"name":"/rust/my/os-checker/tmp/test-fmt/tests/a.rs","mismatches":[{"origin
al_begin_line":1,"original_end_line":2,"expected_begin_line":1,"expected_end_line":1,"original":"fn main() {\n  }\n","expected":"fn main() {}\n"}]}]

stderr=

[test-fmt with Clippy checking] exit statusexit status: 101
stdout={"reason":"compiler-message","package_id":"path+file:///rust/my/os-checker/tmp/test-fmt#0.1.0","manifest_path":"/rust/my/os-checker/tmp/test-fmt/Cargo.toml","target"
:{"kind":["bin"],"crate_types":["bin"],"name":"test-fmt","src_path":"/rust/my/os-checker/tmp/test-fmt/src/main.rs","edition":"2021","doc":true,"doctest":false,"test":true},
"message":{"rendered":"warning: unused variable: `a`\n --> src/main.rs:2:9\n  |\n2 |     let a = 3.14;\n  |         ^ help: if this is intentional, prefix it with an unders
core: `_a`\n  |\n  = note: `#[warn(unused_variables)]` on by default\n\n","$message_type":"diagnostic","children":[{"children":[],"code":null,"level":"note","message":"`#[w
arn(unused_variables)]` on by default","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"if this is intentional, prefix it with an underscore
","rendered":null,"spans":[{"byte_end":21,"byte_start":20,"column_end":10,"column_start":9,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_e
nd":2,"line_start":2,"suggested_replacement":"_a","suggestion_applicability":"MaybeIncorrect","text":[{"highlight_end":10,"highlight_start":9,"text":"    let a = 3.14;"}]}]
}],"code":{"code":"unused_variables","explanation":null},"level":"warning","message":"unused variable: `a`","spans":[{"byte_end":21,"byte_start":20,"column_end":10,"column_
start":9,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":2,"line_start":2,"suggested_replacement":null,"suggestion_applicability":null,
"text":[{"highlight_end":10,"highlight_start":9,"text":"    let a = 3.14;"}]}]}}
{"reason":"compiler-message","package_id":"path+file:///rust/my/os-checker/tmp/test-fmt#0.1.0","manifest_path":"/rust/my/os-checker/tmp/test-fmt/Cargo.toml","target":{"kind
":["bin"],"crate_types":["bin"],"name":"test-fmt","src_path":"/rust/my/os-checker/tmp/test-fmt/src/main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"messag
e":{"rendered":"error: approximate value of `f{32, 64}::consts::PI` found\n --> src/main.rs:2:13\n  |\n2 |     let a = 3.14;\n  |             ^^^^\n  |\n  = help: consider
using the constant directly\n  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#approx_constant\n  = note: `#[deny(clippy::ap
prox_constant)]` on by default\n\n","$message_type":"diagnostic","children":[{"children":[],"code":null,"level":"help","message":"consider using the constant directly","ren
dered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#approx_
constant","rendered":null,"spans":[]},{"children":[],"code":null,"level":"note","message":"`#[deny(clippy::approx_constant)]` on by default","rendered":null,"spans":[]}],"c
ode":{"code":"clippy::approx_constant","explanation":null},"level":"error","message":"approximate value of `f{32, 64}::consts::PI` found","spans":[{"byte_end":28,"byte_star
t":24,"column_end":17,"column_start":13,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":2,"line_start":2,"suggested_replacement":null,"
suggestion_applicability":null,"text":[{"highlight_end":17,"highlight_start":13,"text":"    let a = 3.14;"}]}]}}
{"reason":"compiler-message","package_id":"path+file:///rust/my/os-checker/tmp/test-fmt#0.1.0","manifest_path":"/rust/my/os-checker/tmp/test-fmt/Cargo.toml","target":{"kind
":["bin"],"crate_types":["bin"],"name":"test-fmt","src_path":"/rust/my/os-checker/tmp/test-fmt/src/main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"messag
e":{"rendered":"error: aborting due to 1 previous error; 1 warning emitted\n\n","$message_type":"diagnostic","children":[],"code":null,"level":"error","message":"aborting d
ue to 1 previous error; 1 warning emitted","spans":[]}}
{"reason":"build-finished","success":false}

stderr=    Checking test-fmt v0.1.0 (/rust/my/os-checker/tmp/test-fmt)
error: could not compile `test-fmt` (bin "test-fmt") due to 2 previous errors; 1 warning emitted