fix: ensure checkers like rustfmt are installed with pinned toolchain
Without specifying them, we'll meet errors:
2024-07-28T08:43:06.038841Z DEBUG os_checker::repo::cmd: expr=Cmd(["cargo", "clippy", "--no-deps", "--message-format=json", "--manifest-path", "/ci/check/os-checker-test-suite/Cargo.toml"])
Error: 无法解析 rustfmt 的标准输出：stdout=
""
stderr=error: 'cargo-fmt' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'.
To install, run `rustup component add rustfmt`
resolve=
Resolve { package: Package { name: "os-checker-test-suite", cargo_toml: "./Cargo.toml", workspace_root (file name): "os-checker-test-suite" }, checker: Fmt, expr: Cmd(["cargo", "fmt", "--manifest-path", "/ci/check/os-checker-test-suite/Cargo.toml", "--", "--emit=json"]) }
Caused by:
    EOF while parsing a value at line 1 column 0
Location:
    src/run_checker/mod.rs:134:48