fix(ci): cp assets/repos-ui.json ~/check
Error: 从 `repos-ui.json` 读取仓库列表失败！请输入正确的 json 路径。
Caused by:
2024-09-04T08:17:37.598754Z TRACE os_checker::cli: arguments=Args { sub_args: Batch(ArgsBatch { config: ["repos-ui.json"], out_dir: "/home/runner/check/batch", size: 3 }) }
    No such file or directory (os error 2)
Location:
    src/config/mod.rs:100:14
make: *** [Makefile:30: batch] Error 1