fix(ci): 在单独的目录 ~/check 下运行 os-checker
Error: 无法解析 `repos-default/kern-crates/driver_pci` 内的 Rust 项目布局

Caused by:
    无法读取 cargo metadata 的结果：`cargo metadata` exited with an error: error: current package believes it's in a workspace when it's not:
    current:   /home/runner/work/os-checker/os-checker/assets/repos-default/kern-crates/driver_pci/Cargo.toml
    workspace: /home/runner/work/os-checker/os-checker/Cargo.toml

    this may be fixable by adding `assets/repos-default/kern-crates/driver_pci` to the `workspace.members` array of the manifest located at: /home/runner/work/os-checker/os-checker/Cargo.toml
    Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.